//prototypes
void compute_next_locations();

void compute_next_locations(){
    switch(total_pulling_motors){
        case 1:
            ax1[1] = ((cy - ay[1])*(-(cy*xiAnchor*ax[1]) + cx*xiAnchor*ay[1]))/xiCargoRotation + (xiAnchor*(-cz + az[1])*(cz*ax[1] - cx*az[1]))/xiCargoRotation + (dt*(pow(cy,2)*xiAnchor + pow(cz,2)*xiAnchor - xiCargoRotation - 2*cy*xiAnchor*ay[1] + xiAnchor*pow(ay[1],2) - 2*cz*xiAnchor*az[1] + xiAnchor*pow(az[1],2))*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/(xiAnchor*xiCargoRotation) - (dt*(cx - ax[1])*(cy - ay[1])*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/xiCargoRotation - (dt*(cx - ax[1])*(cz - az[1])*((xiAnchor*az[1])/dt - FmTangentialz[1]))/xiCargoRotation;

            ay1[1] = ((-cx + ax[1])*(-(cy*xiAnchor*ax[1]) + cx*xiAnchor*ay[1]))/xiCargoRotation + ((cz - az[1])*(-(cz*xiAnchor*ay[1]) + cy*xiAnchor*az[1]))/xiCargoRotation - (dt*(cx - ax[1])*(cy - ay[1])*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/xiCargoRotation + (dt*(pow(cx,2)*xiAnchor + pow(cz,2)*xiAnchor - xiCargoRotation - 2*cx*xiAnchor*ax[1] + xiAnchor*pow(ax[1],2) - 2*cz*xiAnchor*az[1] + xiAnchor*pow(az[1],2))*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/(xiAnchor*xiCargoRotation) - (dt*(cy - ay[1])*(cz - az[1])*((xiAnchor*az[1])/dt - FmTangentialz[1]))/xiCargoRotation;

            az1[1] = (xiAnchor*(cx - ax[1])*(cz*ax[1] - cx*az[1]))/xiCargoRotation + ((-cy + ay[1])*(-(cz*xiAnchor*ay[1]) + cy*xiAnchor*az[1]))/xiCargoRotation - (dt*(cx - ax[1])*(cz - az[1])*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/xiCargoRotation - (dt*(cy - ay[1])*(cz - az[1])*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/xiCargoRotation + (dt*(pow(cx,2)*xiAnchor + pow(cy,2)*xiAnchor - xiCargoRotation - 2*cx*xiAnchor*ax[1] + xiAnchor*pow(ax[1],2) - 2*cy*xiAnchor*ay[1] + xiAnchor*pow(ay[1],2))*((xiAnchor*az[1])/dt - FmTangentialz[1]))/(xiAnchor*xiCargoRotation);

            cx1 = (-2*xiAnchor*(cy - ay[1])*(-(cy*xiAnchor*ax[1]) + cx*xiAnchor*ay[1]))/(xiCargoRotation*xiCargoTranslation) + (2*pow(xiAnchor,2)*(cz - az[1])*(cz*ax[1] - cx*az[1]))/(xiCargoRotation*xiCargoTranslation) - (cx*xiCargoTranslation + xiAnchor*ax[1] - dt*(fStericx + fTrapx + FmRx[1]))/xiCargoTranslation + (dt*(-2*pow(cy,2)*xiAnchor - 2*pow(cz,2)*xiAnchor + xiCargoRotation + 4*cy*xiAnchor*ay[1] - 2*xiAnchor*pow(ay[1],2) + 4*cz*xiAnchor*az[1] - 2*xiAnchor*pow(az[1],2))*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/(xiCargoRotation*xiCargoTranslation) + (2*dt*xiAnchor*(cx - ax[1])*(cy - ay[1])*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/(xiCargoRotation*xiCargoTranslation) + (2*dt*xiAnchor*(cx - ax[1])*(cz - az[1])*((xiAnchor*az[1])/dt - FmTangentialz[1]))/(xiCargoRotation*xiCargoTranslation);

            cy1 = (2*xiAnchor*(cx - ax[1])*(-(cy*xiAnchor*ax[1]) + cx*xiAnchor*ay[1]))/(xiCargoRotation*xiCargoTranslation) - (2*xiAnchor*(cz - az[1])*(-(cz*xiAnchor*ay[1]) + cy*xiAnchor*az[1]))/(xiCargoRotation*xiCargoTranslation) - (cy*xiCargoTranslation + xiAnchor*ay[1] - dt*(fStericy + fTrapy + FmRy[1]))/xiCargoTranslation + (2*dt*xiAnchor*(cx - ax[1])*(cy - ay[1])*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/(xiCargoRotation*xiCargoTranslation) + (dt*(-2*pow(cx,2)*xiAnchor - 2*pow(cz,2)*xiAnchor + xiCargoRotation + 4*cx*xiAnchor*ax[1] - 2*xiAnchor*pow(ax[1],2) + 4*cz*xiAnchor*az[1] - 2*xiAnchor*pow(az[1],2))*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/(xiCargoRotation*xiCargoTranslation) + (2*dt*xiAnchor*(cy - ay[1])*(cz - az[1])*((xiAnchor*az[1])/dt - FmTangentialz[1]))/(xiCargoRotation*xiCargoTranslation);

            cz1 = (-2*pow(xiAnchor,2)*(cx - ax[1])*(cz*ax[1] - cx*az[1]))/(xiCargoRotation*xiCargoTranslation) + (2*xiAnchor*(cy - ay[1])*(-(cz*xiAnchor*ay[1]) + cy*xiAnchor*az[1]))/(xiCargoRotation*xiCargoTranslation) - (cz*xiCargoTranslation + xiAnchor*az[1] - dt*(fStericz + fTrapz + FmRz[1]))/xiCargoTranslation + (2*dt*xiAnchor*(cx - ax[1])*(cz - az[1])*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/(xiCargoRotation*xiCargoTranslation) + (2*dt*xiAnchor*(cy - ay[1])*(cz - az[1])*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/(xiCargoRotation*xiCargoTranslation) + (dt*(-2*pow(cx,2)*xiAnchor - 2*pow(cy,2)*xiAnchor + xiCargoRotation + 4*cx*xiAnchor*ax[1] - 2*xiAnchor*pow(ax[1],2) + 4*cy*xiAnchor*ay[1] - 2*xiAnchor*pow(ay[1],2))*((xiAnchor*az[1])/dt - FmTangentialz[1]))/(xiCargoRotation*xiCargoTranslation);

            omegax = -((-(cz*xiAnchor*ay[1]) + cy*xiAnchor*az[1])/(dt*xiCargoRotation)) + ((-cz + az[1])*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/xiCargoRotation + ((cy - ay[1])*((xiAnchor*az[1])/dt - FmTangentialz[1]))/xiCargoRotation;

            omegay = -((xiAnchor*(cz*ax[1] - cx*az[1]))/(dt*xiCargoRotation)) + ((cz - az[1])*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/xiCargoRotation + ((-cx + ax[1])*((xiAnchor*az[1])/dt - FmTangentialz[1]))/xiCargoRotation;

            omegaz = -((-(cy*xiAnchor*ax[1]) + cx*xiAnchor*ay[1])/(dt*xiCargoRotation)) + ((-cy + ay[1])*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/xiCargoRotation + ((cx - ax[1])*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/xiCargoRotation;

            break;

        case 2:
            ax1[1] = (xiAnchor*(cy - ay[1])*(-(cy*(ax[1] + ax[2])) + cx*(ay[1] + ay[2])))/xiCargoRotation + (xiAnchor*(-cz + az[1])*(cz*(ax[1] + ax[2]) - cx*(az[1] + az[2])))/xiCargoRotation + (dt*(pow(cy,2)*xiAnchor + pow(cz,2)*xiAnchor - xiCargoRotation - 2*cy*xiAnchor*ay[1] + xiAnchor*pow(ay[1],2) - 2*cz*xiAnchor*az[1] + xiAnchor*pow(az[1],2))*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/(xiAnchor*xiCargoRotation) + (dt*(pow(cy,2) + pow(cz,2) + ay[1]*ay[2] - cy*(ay[1] + ay[2]) + az[1]*az[2] - cz*(az[1] + az[2]))*((xiAnchor*ax[2])/dt - FmTangentialx[2]))/xiCargoRotation - (dt*(cx - ax[1])*(cy - ay[1])*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/xiCargoRotation - (dt*(cx - ax[2])*(cy - ay[1])*((xiAnchor*ay[2])/dt - FmTangentialy[2]))/xiCargoRotation - (dt*(cx - ax[1])*(cz - az[1])*((xiAnchor*az[1])/dt - FmTangentialz[1]))/xiCargoRotation - (dt*(cx - ax[2])*(cz - az[1])*((xiAnchor*az[2])/dt - FmTangentialz[2]))/xiCargoRotation;

            ay1[1] = (xiAnchor*(-cx + ax[1])*(-(cy*(ax[1] + ax[2])) + cx*(ay[1] + ay[2])))/xiCargoRotation + (xiAnchor*(cz - az[1])*(-(cz*(ay[1] + ay[2])) + cy*(az[1] + az[2])))/xiCargoRotation - (dt*(cx - ax[1])*(cy - ay[1])*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/xiCargoRotation - (dt*(cx - ax[1])*(cy - ay[2])*((xiAnchor*ax[2])/dt - FmTangentialx[2]))/xiCargoRotation + (dt*(pow(cx,2)*xiAnchor + pow(cz,2)*xiAnchor - xiCargoRotation - 2*cx*xiAnchor*ax[1] + xiAnchor*pow(ax[1],2) - 2*cz*xiAnchor*az[1] + xiAnchor*pow(az[1],2))*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/(xiAnchor*xiCargoRotation) + (dt*(pow(cx,2) + pow(cz,2) + ax[1]*ax[2] - cx*(ax[1] + ax[2]) + az[1]*az[2] - cz*(az[1] + az[2]))*((xiAnchor*ay[2])/dt - FmTangentialy[2]))/xiCargoRotation - (dt*(cy - ay[1])*(cz - az[1])*((xiAnchor*az[1])/dt - FmTangentialz[1]))/xiCargoRotation - (dt*(cy - ay[2])*(cz - az[1])*((xiAnchor*az[2])/dt - FmTangentialz[2]))/xiCargoRotation;

            az1[1] = (xiAnchor*(cx - ax[1])*(cz*(ax[1] + ax[2]) - cx*(az[1] + az[2])))/xiCargoRotation + (xiAnchor*(-cy + ay[1])*(-(cz*(ay[1] + ay[2])) + cy*(az[1] + az[2])))/xiCargoRotation - (dt*(cx - ax[1])*(cz - az[1])*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/xiCargoRotation - (dt*(cx - ax[1])*(cz - az[2])*((xiAnchor*ax[2])/dt - FmTangentialx[2]))/xiCargoRotation - (dt*(cy - ay[1])*(cz - az[1])*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/xiCargoRotation - (dt*(cy - ay[1])*(cz - az[2])*((xiAnchor*ay[2])/dt - FmTangentialy[2]))/xiCargoRotation + (dt*(pow(cx,2)*xiAnchor + pow(cy,2)*xiAnchor - xiCargoRotation - 2*cx*xiAnchor*ax[1] + xiAnchor*pow(ax[1],2) - 2*cy*xiAnchor*ay[1] + xiAnchor*pow(ay[1],2))*((xiAnchor*az[1])/dt - FmTangentialz[1]))/(xiAnchor*xiCargoRotation) + (dt*(pow(cx,2) + pow(cy,2) + ax[1]*ax[2] - cx*(ax[1] + ax[2]) + ay[1]*ay[2] - cy*(ay[1] + ay[2]))*((xiAnchor*az[2])/dt - FmTangentialz[2]))/xiCargoRotation;

            ax1[2] = (xiAnchor*(cy - ay[2])*(-(cy*(ax[1] + ax[2])) + cx*(ay[1] + ay[2])))/xiCargoRotation + (xiAnchor*(-cz + az[2])*(cz*(ax[1] + ax[2]) - cx*(az[1] + az[2])))/xiCargoRotation + (dt*(pow(cy,2) + pow(cz,2) + ay[1]*ay[2] - cy*(ay[1] + ay[2]) + az[1]*az[2] - cz*(az[1] + az[2]))*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/xiCargoRotation + (dt*(pow(cy,2)*xiAnchor + pow(cz,2)*xiAnchor - xiCargoRotation - 2*cy*xiAnchor*ay[2] + xiAnchor*pow(ay[2],2) - 2*cz*xiAnchor*az[2] + xiAnchor*pow(az[2],2))*((xiAnchor*ax[2])/dt - FmTangentialx[2]))/(xiAnchor*xiCargoRotation) - (dt*(cx - ax[1])*(cy - ay[2])*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/xiCargoRotation - (dt*(cx - ax[2])*(cy - ay[2])*((xiAnchor*ay[2])/dt - FmTangentialy[2]))/xiCargoRotation - (dt*(cx - ax[1])*(cz - az[2])*((xiAnchor*az[1])/dt - FmTangentialz[1]))/xiCargoRotation - (dt*(cx - ax[2])*(cz - az[2])*((xiAnchor*az[2])/dt - FmTangentialz[2]))/xiCargoRotation;

            ay1[2] = (xiAnchor*(-cx + ax[2])*(-(cy*(ax[1] + ax[2])) + cx*(ay[1] + ay[2])))/xiCargoRotation + (xiAnchor*(cz - az[2])*(-(cz*(ay[1] + ay[2])) + cy*(az[1] + az[2])))/xiCargoRotation - (dt*(cx - ax[2])*(cy - ay[1])*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/xiCargoRotation - (dt*(cx - ax[2])*(cy - ay[2])*((xiAnchor*ax[2])/dt - FmTangentialx[2]))/xiCargoRotation + (dt*(pow(cx,2) + pow(cz,2) + ax[1]*ax[2] - cx*(ax[1] + ax[2]) + az[1]*az[2] - cz*(az[1] + az[2]))*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/xiCargoRotation + (dt*(pow(cx,2)*xiAnchor + pow(cz,2)*xiAnchor - xiCargoRotation - 2*cx*xiAnchor*ax[2] + xiAnchor*pow(ax[2],2) - 2*cz*xiAnchor*az[2] + xiAnchor*pow(az[2],2))*((xiAnchor*ay[2])/dt - FmTangentialy[2]))/(xiAnchor*xiCargoRotation) - (dt*(cy - ay[1])*(cz - az[2])*((xiAnchor*az[1])/dt - FmTangentialz[1]))/xiCargoRotation - (dt*(cy - ay[2])*(cz - az[2])*((xiAnchor*az[2])/dt - FmTangentialz[2]))/xiCargoRotation;

            az1[2] = (xiAnchor*(cx - ax[2])*(cz*(ax[1] + ax[2]) - cx*(az[1] + az[2])))/xiCargoRotation + (xiAnchor*(-cy + ay[2])*(-(cz*(ay[1] + ay[2])) + cy*(az[1] + az[2])))/xiCargoRotation - (dt*(cx - ax[2])*(cz - az[1])*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/xiCargoRotation - (dt*(cx - ax[2])*(cz - az[2])*((xiAnchor*ax[2])/dt - FmTangentialx[2]))/xiCargoRotation - (dt*(cy - ay[2])*(cz - az[1])*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/xiCargoRotation - (dt*(cy - ay[2])*(cz - az[2])*((xiAnchor*ay[2])/dt - FmTangentialy[2]))/xiCargoRotation + (dt*(pow(cx,2) + pow(cy,2) + ax[1]*ax[2] - cx*(ax[1] + ax[2]) + ay[1]*ay[2] - cy*(ay[1] + ay[2]))*((xiAnchor*az[1])/dt - FmTangentialz[1]))/xiCargoRotation + (dt*(pow(cx,2)*xiAnchor + pow(cy,2)*xiAnchor - xiCargoRotation - 2*cx*xiAnchor*ax[2] + xiAnchor*pow(ax[2],2) - 2*cy*xiAnchor*ay[2] + xiAnchor*pow(ay[2],2))*((xiAnchor*az[2])/dt - FmTangentialz[2]))/(xiAnchor*xiCargoRotation);

            cx1 = (2*pow(xiAnchor,2)*(-2*cy + ay[1] + ay[2])*(-(cy*(ax[1] + ax[2])) + cx*(ay[1] + ay[2])))/(xiCargoRotation*xiCargoTranslation) + (2*pow(xiAnchor,2)*(2*cz - az[1] - az[2])*(cz*(ax[1] + ax[2]) - cx*(az[1] + az[2])))/(xiCargoRotation*xiCargoTranslation) - (cx*xiCargoTranslation + xiAnchor*(ax[1] + ax[2]) - dt*(fStericx + fTrapx + FmRx[1] + FmRx[2]))/xiCargoTranslation + (dt*(-4*pow(cy,2)*xiAnchor - 4*pow(cz,2)*xiAnchor + xiCargoRotation - 2*xiAnchor*pow(ay[1],2) - 2*xiAnchor*ay[1]*ay[2] + 2*cy*xiAnchor*(3*ay[1] + ay[2]) - 2*xiAnchor*pow(az[1],2) - 2*xiAnchor*az[1]*az[2] + 2*cz*xiAnchor*(3*az[1] + az[2]))*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/(xiCargoRotation*xiCargoTranslation) + (dt*(-4*pow(cy,2)*xiAnchor - 4*pow(cz,2)*xiAnchor + xiCargoRotation - 2*xiAnchor*ay[1]*ay[2] - 2*xiAnchor*pow(ay[2],2) + 2*cy*xiAnchor*(ay[1] + 3*ay[2]) - 2*xiAnchor*az[1]*az[2] - 2*xiAnchor*pow(az[2],2) + 2*cz*xiAnchor*(az[1] + 3*az[2]))*((xiAnchor*ax[2])/dt - FmTangentialx[2]))/(xiCargoRotation*xiCargoTranslation) + (2*dt*xiAnchor*(cx - ax[1])*(2*cy - ay[1] - ay[2])*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/(xiCargoRotation*xiCargoTranslation) + (2*dt*xiAnchor*(cx - ax[2])*(2*cy - ay[1] - ay[2])*((xiAnchor*ay[2])/dt - FmTangentialy[2]))/(xiCargoRotation*xiCargoTranslation) + (2*dt*xiAnchor*(cx - ax[1])*(2*cz - az[1] - az[2])*((xiAnchor*az[1])/dt - FmTangentialz[1]))/(xiCargoRotation*xiCargoTranslation) + (2*dt*xiAnchor*(cx - ax[2])*(2*cz - az[1] - az[2])*((xiAnchor*az[2])/dt - FmTangentialz[2]))/(xiCargoRotation*xiCargoTranslation);

            cy1 = (2*pow(xiAnchor,2)*(2*cx - ax[1] - ax[2])*(-(cy*(ax[1] + ax[2])) + cx*(ay[1] + ay[2])))/(xiCargoRotation*xiCargoTranslation) + (2*pow(xiAnchor,2)*(-2*cz + az[1] + az[2])*(-(cz*(ay[1] + ay[2])) + cy*(az[1] + az[2])))/(xiCargoRotation*xiCargoTranslation) - (cy*xiCargoTranslation + xiAnchor*(ay[1] + ay[2]) - dt*(fStericy + fTrapy + FmRy[1] + FmRy[2]))/xiCargoTranslation + (2*dt*xiAnchor*(2*cx - ax[1] - ax[2])*(cy - ay[1])*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/(xiCargoRotation*xiCargoTranslation) + (2*dt*xiAnchor*(2*cx - ax[1] - ax[2])*(cy - ay[2])*((xiAnchor*ax[2])/dt - FmTangentialx[2]))/(xiCargoRotation*xiCargoTranslation) + (dt*(-4*pow(cx,2)*xiAnchor - 4*pow(cz,2)*xiAnchor + xiCargoRotation - 2*xiAnchor*pow(ax[1],2) - 2*xiAnchor*ax[1]*ax[2] + 2*cx*xiAnchor*(3*ax[1] + ax[2]) - 2*xiAnchor*pow(az[1],2) - 2*xiAnchor*az[1]*az[2] + 2*cz*xiAnchor*(3*az[1] + az[2]))*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/(xiCargoRotation*xiCargoTranslation) + (dt*(-4*pow(cx,2)*xiAnchor - 4*pow(cz,2)*xiAnchor + xiCargoRotation - 2*xiAnchor*ax[1]*ax[2] - 2*xiAnchor*pow(ax[2],2) + 2*cx*xiAnchor*(ax[1] + 3*ax[2]) - 2*xiAnchor*az[1]*az[2] - 2*xiAnchor*pow(az[2],2) + 2*cz*xiAnchor*(az[1] + 3*az[2]))*((xiAnchor*ay[2])/dt - FmTangentialy[2]))/(xiCargoRotation*xiCargoTranslation) + (2*dt*xiAnchor*(cy - ay[1])*(2*cz - az[1] - az[2])*((xiAnchor*az[1])/dt - FmTangentialz[1]))/(xiCargoRotation*xiCargoTranslation) + (2*dt*xiAnchor*(cy - ay[2])*(2*cz - az[1] - az[2])*((xiAnchor*az[2])/dt - FmTangentialz[2]))/(xiCargoRotation*xiCargoTranslation);

            cz1 = (2*pow(xiAnchor,2)*(-2*cx + ax[1] + ax[2])*(cz*(ax[1] + ax[2]) - cx*(az[1] + az[2])))/(xiCargoRotation*xiCargoTranslation) + (2*pow(xiAnchor,2)*(2*cy - ay[1] - ay[2])*(-(cz*(ay[1] + ay[2])) + cy*(az[1] + az[2])))/(xiCargoRotation*xiCargoTranslation) - (cz*xiCargoTranslation + xiAnchor*(az[1] + az[2]) - dt*(fStericz + fTrapz + FmRz[1] + FmRz[2]))/xiCargoTranslation + (2*dt*xiAnchor*(2*cx - ax[1] - ax[2])*(cz - az[1])*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/(xiCargoRotation*xiCargoTranslation) + (2*dt*xiAnchor*(2*cx - ax[1] - ax[2])*(cz - az[2])*((xiAnchor*ax[2])/dt - FmTangentialx[2]))/(xiCargoRotation*xiCargoTranslation) + (2*dt*xiAnchor*(2*cy - ay[1] - ay[2])*(cz - az[1])*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/(xiCargoRotation*xiCargoTranslation) + (2*dt*xiAnchor*(2*cy - ay[1] - ay[2])*(cz - az[2])*((xiAnchor*ay[2])/dt - FmTangentialy[2]))/(xiCargoRotation*xiCargoTranslation) + (dt*(-4*pow(cx,2)*xiAnchor - 4*pow(cy,2)*xiAnchor + xiCargoRotation - 2*xiAnchor*pow(ax[1],2) - 2*xiAnchor*ax[1]*ax[2] + 2*cx*xiAnchor*(3*ax[1] + ax[2]) - 2*xiAnchor*pow(ay[1],2) - 2*xiAnchor*ay[1]*ay[2] + 2*cy*xiAnchor*(3*ay[1] + ay[2]))*((xiAnchor*az[1])/dt - FmTangentialz[1]))/(xiCargoRotation*xiCargoTranslation) + (dt*(-4*pow(cx,2)*xiAnchor - 4*pow(cy,2)*xiAnchor + xiCargoRotation - 2*xiAnchor*ax[1]*ax[2] - 2*xiAnchor*pow(ax[2],2) + 2*cx*xiAnchor*(ax[1] + 3*ax[2]) - 2*xiAnchor*ay[1]*ay[2] - 2*xiAnchor*pow(ay[2],2) + 2*cy*xiAnchor*(ay[1] + 3*ay[2]))*((xiAnchor*az[2])/dt - FmTangentialz[2]))/(xiCargoRotation*xiCargoTranslation);

            omegax = -((xiAnchor*(-(cz*(ay[1] + ay[2])) + cy*(az[1] + az[2])))/(dt*xiCargoRotation)) + ((-cz + az[1])*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/xiCargoRotation + ((-cz + az[2])*((xiAnchor*ay[2])/dt - FmTangentialy[2]))/xiCargoRotation + ((cy - ay[1])*((xiAnchor*az[1])/dt - FmTangentialz[1]))/xiCargoRotation + ((cy - ay[2])*((xiAnchor*az[2])/dt - FmTangentialz[2]))/xiCargoRotation;

            omegay = -((xiAnchor*(cz*(ax[1] + ax[2]) - cx*(az[1] + az[2])))/(dt*xiCargoRotation)) + ((cz - az[1])*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/xiCargoRotation + ((cz - az[2])*((xiAnchor*ax[2])/dt - FmTangentialx[2]))/xiCargoRotation + ((-cx + ax[1])*((xiAnchor*az[1])/dt - FmTangentialz[1]))/xiCargoRotation + ((-cx + ax[2])*((xiAnchor*az[2])/dt - FmTangentialz[2]))/xiCargoRotation;

            omegaz = -((xiAnchor*(-(cy*(ax[1] + ax[2])) + cx*(ay[1] + ay[2])))/(dt*xiCargoRotation)) + ((-cy + ay[1])*((xiAnchor*ax[1])/dt - FmTangentialx[1]))/xiCargoRotation + ((-cy + ay[2])*((xiAnchor*ax[2])/dt - FmTangentialx[2]))/xiCargoRotation + ((cx - ax[1])*((xiAnchor*ay[1])/dt - FmTangentialy[1]))/xiCargoRotation + ((cx - ax[2])*((xiAnchor*ay[2])/dt - FmTangentialy[2]))/xiCargoRotation;

            break;

        default:
            printf("Bad value for total_pulling_motors\n");
    }
}
