//prototypes
void stochastic_equations();

void stochastic_equations(){
    switch(total_motors){
        case 0:
            c1[0] = c[0] + sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[0] + dt*muCargoTranslation*(Fsteric[0] + Ftrap[0]);

            c1[1] = c[1] + sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[1] + dt*muCargoTranslation*(Fsteric[1] + Ftrap[1]);

            c1[2] = c[2] + sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[2] + dt*muCargoTranslation*(Fsteric[2] + Ftrap[2]);

//            theta1[0] = sqrt(2)*sqrt(DCargoRotation)*sqrt(dt)*Rbc[0] + theta[0] + dt*muCargoRotation*TorqeExt[0];

//            theta1[1] = sqrt(2)*sqrt(DCargoRotation)*sqrt(dt)*Rbc[1] + theta[1] + dt*muCargoRotation*TorqeExt[1];

//            theta1[2] = sqrt(2)*sqrt(DCargoRotation)*sqrt(dt)*Rbc[2] + theta[2] + dt*muCargoRotation*TorqeExt[2];

            break;

        case 1:
            a1[0][0] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[0] + a[0][0] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[2] + sqrt(dt)*muCargoRotation*TorqeExt[2])*(c[1] - a[0][1]) - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[1] + sqrt(dt)*muCargoRotation*TorqeExt[1])*(c[2] - a[0][2]) + dt*muCargoTranslation*(Fsteric[0] + Ftrap[0] + FmRadial[0][0]) + (sqrt(dt)*(muCargoTranslation + muAnchor[0] + muCargoRotation*(pow(c[1],2) + pow(c[2],2) - 2*c[1]*a[0][1] + pow(a[0][1],2) - 2*c[2]*a[0][2] + pow(a[0][2],2)))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[1] - a[0][1])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[2] - a[0][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0];

            a1[0][1] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[1] - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[2] + sqrt(dt)*muCargoRotation*TorqeExt[2])*(c[0] - a[0][0]) + a[0][1] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[0] + sqrt(dt)*muCargoRotation*TorqeExt[0])*(c[2] - a[0][2]) + dt*muCargoTranslation*(Fsteric[1] + Ftrap[1] + FmRadial[0][1]) - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[1] - a[0][1])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muAnchor[0] + muCargoRotation*(pow(c[0],2) + pow(c[2],2) - 2*c[0]*a[0][0] + pow(a[0][0],2) - 2*c[2]*a[0][2] + pow(a[0][2],2)))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[2] - a[0][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0];

            a1[0][2] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[2] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[1] + sqrt(dt)*muCargoRotation*TorqeExt[1])*(c[0] - a[0][0]) - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[0] + sqrt(dt)*muCargoRotation*TorqeExt[0])*(c[1] - a[0][1]) + a[0][2] + dt*muCargoTranslation*(Fsteric[2] + Ftrap[2] + FmRadial[0][2]) - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[2] - a[0][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[2] - a[0][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muAnchor[0] + muCargoRotation*(pow(c[0],2) + pow(c[1],2) - 2*c[0]*a[0][0] + pow(a[0][0],2) - 2*c[1]*a[0][1] + pow(a[0][1],2)))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0];

            c1[0] = c[0] + sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[0] + dt*muCargoTranslation*Fsteric[0] + dt*muCargoTranslation*Ftrap[0] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[0])*Dba[0][0])/muAnchor[0] + dt*muCargoTranslation*FmRadial[0][0] + dt*muCargoTranslation*FmTangential[0][0];

            c1[1] = c[1] + sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[1] + dt*muCargoTranslation*Fsteric[1] + dt*muCargoTranslation*Ftrap[1] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[0])*Dba[0][1])/muAnchor[0] + dt*muCargoTranslation*FmRadial[0][1] + dt*muCargoTranslation*FmTangential[0][1];

            c1[2] = c[2] + sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[2] + dt*muCargoTranslation*Fsteric[2] + dt*muCargoTranslation*Ftrap[2] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[0])*Dba[0][2])/muAnchor[0] + dt*muCargoTranslation*FmRadial[0][2] + dt*muCargoTranslation*FmTangential[0][2];

//            theta1[0] = (sqrt(2)*sqrt(DCargoRotation)*sqrt(dt)*muAnchor[0]*Rbc[0] + sqrt(2)*sqrt(dt)*muCargoRotation*sqrt(DAnchor[0])*(c[2]*Dba[0][1] - a[0][2]*Dba[0][1] + (-c[1] + a[0][1])*Dba[0][2]) + muAnchor[0]*(theta[0] + dt*muCargoRotation*(TorqeExt[0] + c[2]*FmTangential[0][1] - a[0][2]*FmTangential[0][1] - c[1]*FmTangential[0][2] + a[0][1]*FmTangential[0][2])))/muAnchor[0];

//            theta1[1] = (sqrt(2)*sqrt(DCargoRotation)*sqrt(dt)*muAnchor[0]*Rbc[1] + sqrt(2)*sqrt(dt)*muCargoRotation*sqrt(DAnchor[0])*(-(c[2]*Dba[0][0]) + a[0][2]*Dba[0][0] + (c[0] - a[0][0])*Dba[0][2]) + muAnchor[0]*(theta[1] + dt*muCargoRotation*(TorqeExt[1] - c[2]*FmTangential[0][0] + a[0][2]*FmTangential[0][0] + c[0]*FmTangential[0][2] - a[0][0]*FmTangential[0][2])))/muAnchor[0];

//            theta1[2] = (sqrt(2)*sqrt(DCargoRotation)*sqrt(dt)*muAnchor[0]*Rbc[2] + sqrt(2)*sqrt(dt)*muCargoRotation*sqrt(DAnchor[0])*(c[1]*Dba[0][0] - a[0][1]*Dba[0][0] + (-c[0] + a[0][0])*Dba[0][1]) + muAnchor[0]*(theta[2] + dt*muCargoRotation*(TorqeExt[2] + c[1]*FmTangential[0][0] - a[0][1]*FmTangential[0][0] - c[0]*FmTangential[0][1] + a[0][0]*FmTangential[0][1])))/muAnchor[0];

            break;

        case 2:
            a1[0][0] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[0] + a[0][0] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[2] + sqrt(dt)*muCargoRotation*TorqeExt[2])*(c[1] - a[0][1]) - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[1] + sqrt(dt)*muCargoRotation*TorqeExt[1])*(c[2] - a[0][2]) + dt*muCargoTranslation*(Fsteric[0] + Ftrap[0] + FmRadial[0][0] + FmRadial[1][0]) + (sqrt(dt)*(muCargoTranslation + muAnchor[0] + muCargoRotation*(pow(c[1],2) + pow(c[2],2) - 2*c[1]*a[0][1] + pow(a[0][1],2) - 2*c[2]*a[0][2] + pow(a[0][2],2)))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[1] - a[0][1])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[2] - a[0][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[1],2) + pow(c[2],2) + a[0][1]*a[1][1] - c[1]*(a[0][1] + a[1][1]) + a[0][2]*a[1][2] - c[2]*(a[0][2] + a[1][2])))*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][0] + sqrt(dt)*muAnchor[1]*FmTangential[1][0]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[0] - a[1][0])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][1] + sqrt(dt)*muAnchor[1]*FmTangential[1][1]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[2] - a[0][2])*(c[0] - a[1][0])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][2] + sqrt(dt)*muAnchor[1]*FmTangential[1][2]))/muAnchor[1];

            a1[0][1] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[1] - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[2] + sqrt(dt)*muCargoRotation*TorqeExt[2])*(c[0] - a[0][0]) + a[0][1] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[0] + sqrt(dt)*muCargoRotation*TorqeExt[0])*(c[2] - a[0][2]) + dt*muCargoTranslation*(Fsteric[1] + Ftrap[1] + FmRadial[0][1] + FmRadial[1][1]) - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[1] - a[0][1])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muAnchor[0] + muCargoRotation*(pow(c[0],2) + pow(c[2],2) - 2*c[0]*a[0][0] + pow(a[0][0],2) - 2*c[2]*a[0][2] + pow(a[0][2],2)))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[2] - a[0][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[1] - a[1][1])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][0] + sqrt(dt)*muAnchor[1]*FmTangential[1][0]))/muAnchor[1] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[0],2) + pow(c[2],2) + a[0][0]*a[1][0] - c[0]*(a[0][0] + a[1][0]) + a[0][2]*a[1][2] - c[2]*(a[0][2] + a[1][2])))*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][1] + sqrt(dt)*muAnchor[1]*FmTangential[1][1]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[2] - a[0][2])*(c[1] - a[1][1])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][2] + sqrt(dt)*muAnchor[1]*FmTangential[1][2]))/muAnchor[1];

            a1[0][2] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[2] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[1] + sqrt(dt)*muCargoRotation*TorqeExt[1])*(c[0] - a[0][0]) - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[0] + sqrt(dt)*muCargoRotation*TorqeExt[0])*(c[1] - a[0][1]) + a[0][2] + dt*muCargoTranslation*(Fsteric[2] + Ftrap[2] + FmRadial[0][2] + FmRadial[1][2]) - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[2] - a[0][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[2] - a[0][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muAnchor[0] + muCargoRotation*(pow(c[0],2) + pow(c[1],2) - 2*c[0]*a[0][0] + pow(a[0][0],2) - 2*c[1]*a[0][1] + pow(a[0][1],2)))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[2] - a[1][2])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][0] + sqrt(dt)*muAnchor[1]*FmTangential[1][0]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[2] - a[1][2])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][1] + sqrt(dt)*muAnchor[1]*FmTangential[1][1]))/muAnchor[1] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[0],2) + pow(c[1],2) + a[0][0]*a[1][0] - c[0]*(a[0][0] + a[1][0]) + a[0][1]*a[1][1] - c[1]*(a[0][1] + a[1][1])))*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][2] + sqrt(dt)*muAnchor[1]*FmTangential[1][2]))/muAnchor[1];

            a1[1][0] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[0] + a[1][0] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[2] + sqrt(dt)*muCargoRotation*TorqeExt[2])*(c[1] - a[1][1]) - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[1] + sqrt(dt)*muCargoRotation*TorqeExt[1])*(c[2] - a[1][2]) + dt*muCargoTranslation*(Fsteric[0] + Ftrap[0] + FmRadial[0][0] + FmRadial[1][0]) + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[1],2) + pow(c[2],2) + a[0][1]*a[1][1] - c[1]*(a[0][1] + a[1][1]) + a[0][2]*a[1][2] - c[2]*(a[0][2] + a[1][2])))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[1] - a[1][1])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[2] - a[1][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muAnchor[1] + muCargoRotation*(pow(c[1],2) + pow(c[2],2) - 2*c[1]*a[1][1] + pow(a[1][1],2) - 2*c[2]*a[1][2] + pow(a[1][2],2)))*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][0] + sqrt(dt)*muAnchor[1]*FmTangential[1][0]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[0] - a[1][0])*(c[1] - a[1][1])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][1] + sqrt(dt)*muAnchor[1]*FmTangential[1][1]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[0] - a[1][0])*(c[2] - a[1][2])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][2] + sqrt(dt)*muAnchor[1]*FmTangential[1][2]))/muAnchor[1];

            a1[1][1] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[1] - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[2] + sqrt(dt)*muCargoRotation*TorqeExt[2])*(c[0] - a[1][0]) + a[1][1] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[0] + sqrt(dt)*muCargoRotation*TorqeExt[0])*(c[2] - a[1][2]) + dt*muCargoTranslation*(Fsteric[1] + Ftrap[1] + FmRadial[0][1] + FmRadial[1][1]) - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[0] - a[1][0])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[0],2) + pow(c[2],2) + a[0][0]*a[1][0] - c[0]*(a[0][0] + a[1][0]) + a[0][2]*a[1][2] - c[2]*(a[0][2] + a[1][2])))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[2] - a[1][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[1][0])*(c[1] - a[1][1])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][0] + sqrt(dt)*muAnchor[1]*FmTangential[1][0]))/muAnchor[1] + (sqrt(dt)*(muCargoTranslation + muAnchor[1] + muCargoRotation*(pow(c[0],2) + pow(c[2],2) - 2*c[0]*a[1][0] + pow(a[1][0],2) - 2*c[2]*a[1][2] + pow(a[1][2],2)))*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][1] + sqrt(dt)*muAnchor[1]*FmTangential[1][1]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[1] - a[1][1])*(c[2] - a[1][2])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][2] + sqrt(dt)*muAnchor[1]*FmTangential[1][2]))/muAnchor[1];

            a1[1][2] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[2] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[1] + sqrt(dt)*muCargoRotation*TorqeExt[1])*(c[0] - a[1][0]) - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[0] + sqrt(dt)*muCargoRotation*TorqeExt[0])*(c[1] - a[1][1]) + a[1][2] + dt*muCargoTranslation*(Fsteric[2] + Ftrap[2] + FmRadial[0][2] + FmRadial[1][2]) - (sqrt(dt)*muCargoRotation*(c[2] - a[0][2])*(c[0] - a[1][0])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[2] - a[0][2])*(c[1] - a[1][1])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[0],2) + pow(c[1],2) + a[0][0]*a[1][0] - c[0]*(a[0][0] + a[1][0]) + a[0][1]*a[1][1] - c[1]*(a[0][1] + a[1][1])))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[1][0])*(c[2] - a[1][2])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][0] + sqrt(dt)*muAnchor[1]*FmTangential[1][0]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[1] - a[1][1])*(c[2] - a[1][2])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][1] + sqrt(dt)*muAnchor[1]*FmTangential[1][1]))/muAnchor[1] + (sqrt(dt)*(muCargoTranslation + muAnchor[1] + muCargoRotation*(pow(c[0],2) + pow(c[1],2) - 2*c[0]*a[1][0] + pow(a[1][0],2) - 2*c[1]*a[1][1] + pow(a[1][1],2)))*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][2] + sqrt(dt)*muAnchor[1]*FmTangential[1][2]))/muAnchor[1];

            c1[0] = c[0] + sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[0] + dt*muCargoTranslation*Fsteric[0] + dt*muCargoTranslation*Ftrap[0] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[0])*Dba[0][0])/muAnchor[0] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[1])*Dba[1][0])/muAnchor[1] + dt*muCargoTranslation*FmRadial[0][0] + dt*muCargoTranslation*FmRadial[1][0] + dt*muCargoTranslation*FmTangential[0][0] + dt*muCargoTranslation*FmTangential[1][0];

            c1[1] = c[1] + sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[1] + dt*muCargoTranslation*Fsteric[1] + dt*muCargoTranslation*Ftrap[1] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[0])*Dba[0][1])/muAnchor[0] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[1])*Dba[1][1])/muAnchor[1] + dt*muCargoTranslation*FmRadial[0][1] + dt*muCargoTranslation*FmRadial[1][1] + dt*muCargoTranslation*FmTangential[0][1] + dt*muCargoTranslation*FmTangential[1][1];

            c1[2] = c[2] + sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[2] + dt*muCargoTranslation*Fsteric[2] + dt*muCargoTranslation*Ftrap[2] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[0])*Dba[0][2])/muAnchor[0] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[1])*Dba[1][2])/muAnchor[1] + dt*muCargoTranslation*FmRadial[0][2] + dt*muCargoTranslation*FmRadial[1][2] + dt*muCargoTranslation*FmTangential[0][2] + dt*muCargoTranslation*FmTangential[1][2];

//            theta1[0] = dt*((sqrt(2)*sqrt(DCargoRotation)*Rbc[0])/sqrt(dt) + theta[0]/dt + muCargoRotation*TorqeExt[0] + muCargoRotation*(c[2] - a[0][2])*((sqrt(2)*sqrt(DAnchor[0])*Dba[0][1])/(sqrt(dt)*muAnchor[0]) + FmTangential[0][1]) + muCargoRotation*(-c[1] + a[0][1])*((sqrt(2)*sqrt(DAnchor[0])*Dba[0][2])/(sqrt(dt)*muAnchor[0]) + FmTangential[0][2]) + muCargoRotation*(c[2] - a[1][2])*((sqrt(2)*sqrt(DAnchor[1])*Dba[1][1])/(sqrt(dt)*muAnchor[1]) + FmTangential[1][1]) + muCargoRotation*(-c[1] + a[1][1])*((sqrt(2)*sqrt(DAnchor[1])*Dba[1][2])/(sqrt(dt)*muAnchor[1]) + FmTangential[1][2]));

//            theta1[1] = dt*((sqrt(2)*sqrt(DCargoRotation)*Rbc[1])/sqrt(dt) + theta[1]/dt + muCargoRotation*TorqeExt[1] + muCargoRotation*(-c[2] + a[0][2])*((sqrt(2)*sqrt(DAnchor[0])*Dba[0][0])/(sqrt(dt)*muAnchor[0]) + FmTangential[0][0]) + muCargoRotation*(c[0] - a[0][0])*((sqrt(2)*sqrt(DAnchor[0])*Dba[0][2])/(sqrt(dt)*muAnchor[0]) + FmTangential[0][2]) + muCargoRotation*(-c[2] + a[1][2])*((sqrt(2)*sqrt(DAnchor[1])*Dba[1][0])/(sqrt(dt)*muAnchor[1]) + FmTangential[1][0]) + muCargoRotation*(c[0] - a[1][0])*((sqrt(2)*sqrt(DAnchor[1])*Dba[1][2])/(sqrt(dt)*muAnchor[1]) + FmTangential[1][2]));

//            theta1[2] = dt*((sqrt(2)*sqrt(DCargoRotation)*Rbc[2])/sqrt(dt) + theta[2]/dt + muCargoRotation*TorqeExt[2] + muCargoRotation*(c[1] - a[0][1])*((sqrt(2)*sqrt(DAnchor[0])*Dba[0][0])/(sqrt(dt)*muAnchor[0]) + FmTangential[0][0]) + muCargoRotation*(-c[0] + a[0][0])*((sqrt(2)*sqrt(DAnchor[0])*Dba[0][1])/(sqrt(dt)*muAnchor[0]) + FmTangential[0][1]) + muCargoRotation*(c[1] - a[1][1])*((sqrt(2)*sqrt(DAnchor[1])*Dba[1][0])/(sqrt(dt)*muAnchor[1]) + FmTangential[1][0]) + muCargoRotation*(-c[0] + a[1][0])*((sqrt(2)*sqrt(DAnchor[1])*Dba[1][1])/(sqrt(dt)*muAnchor[1]) + FmTangential[1][1]));

            break;

        case 3:
            a1[0][0] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[0] + a[0][0] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[2] + sqrt(dt)*muCargoRotation*TorqeExt[2])*(c[1] - a[0][1]) - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[1] + sqrt(dt)*muCargoRotation*TorqeExt[1])*(c[2] - a[0][2]) + dt*muCargoTranslation*(Fsteric[0] + Ftrap[0] + FmRadial[0][0] + FmRadial[1][0] + FmRadial[2][0]) + (sqrt(dt)*(muCargoTranslation + muAnchor[0] + muCargoRotation*(pow(c[1],2) + pow(c[2],2) - 2*c[1]*a[0][1] + pow(a[0][1],2) - 2*c[2]*a[0][2] + pow(a[0][2],2)))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[1] - a[0][1])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[2] - a[0][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[1],2) + pow(c[2],2) + a[0][1]*a[1][1] - c[1]*(a[0][1] + a[1][1]) + a[0][2]*a[1][2] - c[2]*(a[0][2] + a[1][2])))*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][0] + sqrt(dt)*muAnchor[1]*FmTangential[1][0]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[0] - a[1][0])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][1] + sqrt(dt)*muAnchor[1]*FmTangential[1][1]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[2] - a[0][2])*(c[0] - a[1][0])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][2] + sqrt(dt)*muAnchor[1]*FmTangential[1][2]))/muAnchor[1] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[1],2) + pow(c[2],2) + a[0][1]*a[2][1] - c[1]*(a[0][1] + a[2][1]) + a[0][2]*a[2][2] - c[2]*(a[0][2] + a[2][2])))*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][0] + sqrt(dt)*muAnchor[2]*FmTangential[2][0]))/muAnchor[2] - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[0] - a[2][0])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][1] + sqrt(dt)*muAnchor[2]*FmTangential[2][1]))/muAnchor[2] - (sqrt(dt)*muCargoRotation*(c[2] - a[0][2])*(c[0] - a[2][0])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][2] + sqrt(dt)*muAnchor[2]*FmTangential[2][2]))/muAnchor[2];

            a1[0][1] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[1] - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[2] + sqrt(dt)*muCargoRotation*TorqeExt[2])*(c[0] - a[0][0]) + a[0][1] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[0] + sqrt(dt)*muCargoRotation*TorqeExt[0])*(c[2] - a[0][2]) + dt*muCargoTranslation*(Fsteric[1] + Ftrap[1] + FmRadial[0][1] + FmRadial[1][1] + FmRadial[2][1]) - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[1] - a[0][1])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muAnchor[0] + muCargoRotation*(pow(c[0],2) + pow(c[2],2) - 2*c[0]*a[0][0] + pow(a[0][0],2) - 2*c[2]*a[0][2] + pow(a[0][2],2)))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[2] - a[0][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[1] - a[1][1])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][0] + sqrt(dt)*muAnchor[1]*FmTangential[1][0]))/muAnchor[1] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[0],2) + pow(c[2],2) + a[0][0]*a[1][0] - c[0]*(a[0][0] + a[1][0]) + a[0][2]*a[1][2] - c[2]*(a[0][2] + a[1][2])))*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][1] + sqrt(dt)*muAnchor[1]*FmTangential[1][1]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[2] - a[0][2])*(c[1] - a[1][1])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][2] + sqrt(dt)*muAnchor[1]*FmTangential[1][2]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[1] - a[2][1])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][0] + sqrt(dt)*muAnchor[2]*FmTangential[2][0]))/muAnchor[2] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[0],2) + pow(c[2],2) + a[0][0]*a[2][0] - c[0]*(a[0][0] + a[2][0]) + a[0][2]*a[2][2] - c[2]*(a[0][2] + a[2][2])))*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][1] + sqrt(dt)*muAnchor[2]*FmTangential[2][1]))/muAnchor[2] - (sqrt(dt)*muCargoRotation*(c[2] - a[0][2])*(c[1] - a[2][1])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][2] + sqrt(dt)*muAnchor[2]*FmTangential[2][2]))/muAnchor[2];

            a1[0][2] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[2] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[1] + sqrt(dt)*muCargoRotation*TorqeExt[1])*(c[0] - a[0][0]) - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[0] + sqrt(dt)*muCargoRotation*TorqeExt[0])*(c[1] - a[0][1]) + a[0][2] + dt*muCargoTranslation*(Fsteric[2] + Ftrap[2] + FmRadial[0][2] + FmRadial[1][2] + FmRadial[2][2]) - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[2] - a[0][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[2] - a[0][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muAnchor[0] + muCargoRotation*(pow(c[0],2) + pow(c[1],2) - 2*c[0]*a[0][0] + pow(a[0][0],2) - 2*c[1]*a[0][1] + pow(a[0][1],2)))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[2] - a[1][2])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][0] + sqrt(dt)*muAnchor[1]*FmTangential[1][0]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[2] - a[1][2])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][1] + sqrt(dt)*muAnchor[1]*FmTangential[1][1]))/muAnchor[1] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[0],2) + pow(c[1],2) + a[0][0]*a[1][0] - c[0]*(a[0][0] + a[1][0]) + a[0][1]*a[1][1] - c[1]*(a[0][1] + a[1][1])))*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][2] + sqrt(dt)*muAnchor[1]*FmTangential[1][2]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[2] - a[2][2])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][0] + sqrt(dt)*muAnchor[2]*FmTangential[2][0]))/muAnchor[2] - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[2] - a[2][2])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][1] + sqrt(dt)*muAnchor[2]*FmTangential[2][1]))/muAnchor[2] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[0],2) + pow(c[1],2) + a[0][0]*a[2][0] - c[0]*(a[0][0] + a[2][0]) + a[0][1]*a[2][1] - c[1]*(a[0][1] + a[2][1])))*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][2] + sqrt(dt)*muAnchor[2]*FmTangential[2][2]))/muAnchor[2];

            a1[1][0] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[0] + a[1][0] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[2] + sqrt(dt)*muCargoRotation*TorqeExt[2])*(c[1] - a[1][1]) - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[1] + sqrt(dt)*muCargoRotation*TorqeExt[1])*(c[2] - a[1][2]) + dt*muCargoTranslation*(Fsteric[0] + Ftrap[0] + FmRadial[0][0] + FmRadial[1][0] + FmRadial[2][0]) + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[1],2) + pow(c[2],2) + a[0][1]*a[1][1] - c[1]*(a[0][1] + a[1][1]) + a[0][2]*a[1][2] - c[2]*(a[0][2] + a[1][2])))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[1] - a[1][1])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[2] - a[1][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muAnchor[1] + muCargoRotation*(pow(c[1],2) + pow(c[2],2) - 2*c[1]*a[1][1] + pow(a[1][1],2) - 2*c[2]*a[1][2] + pow(a[1][2],2)))*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][0] + sqrt(dt)*muAnchor[1]*FmTangential[1][0]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[0] - a[1][0])*(c[1] - a[1][1])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][1] + sqrt(dt)*muAnchor[1]*FmTangential[1][1]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[0] - a[1][0])*(c[2] - a[1][2])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][2] + sqrt(dt)*muAnchor[1]*FmTangential[1][2]))/muAnchor[1] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[1],2) + pow(c[2],2) + a[1][1]*a[2][1] - c[1]*(a[1][1] + a[2][1]) + a[1][2]*a[2][2] - c[2]*(a[1][2] + a[2][2])))*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][0] + sqrt(dt)*muAnchor[2]*FmTangential[2][0]))/muAnchor[2] - (sqrt(dt)*muCargoRotation*(c[1] - a[1][1])*(c[0] - a[2][0])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][1] + sqrt(dt)*muAnchor[2]*FmTangential[2][1]))/muAnchor[2] - (sqrt(dt)*muCargoRotation*(c[2] - a[1][2])*(c[0] - a[2][0])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][2] + sqrt(dt)*muAnchor[2]*FmTangential[2][2]))/muAnchor[2];

            a1[1][1] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[1] - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[2] + sqrt(dt)*muCargoRotation*TorqeExt[2])*(c[0] - a[1][0]) + a[1][1] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[0] + sqrt(dt)*muCargoRotation*TorqeExt[0])*(c[2] - a[1][2]) + dt*muCargoTranslation*(Fsteric[1] + Ftrap[1] + FmRadial[0][1] + FmRadial[1][1] + FmRadial[2][1]) - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[0] - a[1][0])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[0],2) + pow(c[2],2) + a[0][0]*a[1][0] - c[0]*(a[0][0] + a[1][0]) + a[0][2]*a[1][2] - c[2]*(a[0][2] + a[1][2])))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[2] - a[1][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[1][0])*(c[1] - a[1][1])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][0] + sqrt(dt)*muAnchor[1]*FmTangential[1][0]))/muAnchor[1] + (sqrt(dt)*(muCargoTranslation + muAnchor[1] + muCargoRotation*(pow(c[0],2) + pow(c[2],2) - 2*c[0]*a[1][0] + pow(a[1][0],2) - 2*c[2]*a[1][2] + pow(a[1][2],2)))*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][1] + sqrt(dt)*muAnchor[1]*FmTangential[1][1]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[1] - a[1][1])*(c[2] - a[1][2])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][2] + sqrt(dt)*muAnchor[1]*FmTangential[1][2]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[0] - a[1][0])*(c[1] - a[2][1])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][0] + sqrt(dt)*muAnchor[2]*FmTangential[2][0]))/muAnchor[2] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[0],2) + pow(c[2],2) + a[1][0]*a[2][0] - c[0]*(a[1][0] + a[2][0]) + a[1][2]*a[2][2] - c[2]*(a[1][2] + a[2][2])))*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][1] + sqrt(dt)*muAnchor[2]*FmTangential[2][1]))/muAnchor[2] - (sqrt(dt)*muCargoRotation*(c[2] - a[1][2])*(c[1] - a[2][1])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][2] + sqrt(dt)*muAnchor[2]*FmTangential[2][2]))/muAnchor[2];

            a1[1][2] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[2] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[1] + sqrt(dt)*muCargoRotation*TorqeExt[1])*(c[0] - a[1][0]) - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[0] + sqrt(dt)*muCargoRotation*TorqeExt[0])*(c[1] - a[1][1]) + a[1][2] + dt*muCargoTranslation*(Fsteric[2] + Ftrap[2] + FmRadial[0][2] + FmRadial[1][2] + FmRadial[2][2]) - (sqrt(dt)*muCargoRotation*(c[2] - a[0][2])*(c[0] - a[1][0])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[2] - a[0][2])*(c[1] - a[1][1])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[0],2) + pow(c[1],2) + a[0][0]*a[1][0] - c[0]*(a[0][0] + a[1][0]) + a[0][1]*a[1][1] - c[1]*(a[0][1] + a[1][1])))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[1][0])*(c[2] - a[1][2])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][0] + sqrt(dt)*muAnchor[1]*FmTangential[1][0]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[1] - a[1][1])*(c[2] - a[1][2])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][1] + sqrt(dt)*muAnchor[1]*FmTangential[1][1]))/muAnchor[1] + (sqrt(dt)*(muCargoTranslation + muAnchor[1] + muCargoRotation*(pow(c[0],2) + pow(c[1],2) - 2*c[0]*a[1][0] + pow(a[1][0],2) - 2*c[1]*a[1][1] + pow(a[1][1],2)))*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][2] + sqrt(dt)*muAnchor[1]*FmTangential[1][2]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[0] - a[1][0])*(c[2] - a[2][2])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][0] + sqrt(dt)*muAnchor[2]*FmTangential[2][0]))/muAnchor[2] - (sqrt(dt)*muCargoRotation*(c[1] - a[1][1])*(c[2] - a[2][2])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][1] + sqrt(dt)*muAnchor[2]*FmTangential[2][1]))/muAnchor[2] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[0],2) + pow(c[1],2) + a[1][0]*a[2][0] - c[0]*(a[1][0] + a[2][0]) + a[1][1]*a[2][1] - c[1]*(a[1][1] + a[2][1])))*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][2] + sqrt(dt)*muAnchor[2]*FmTangential[2][2]))/muAnchor[2];

            a1[2][0] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[0] + a[2][0] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[2] + sqrt(dt)*muCargoRotation*TorqeExt[2])*(c[1] - a[2][1]) - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[1] + sqrt(dt)*muCargoRotation*TorqeExt[1])*(c[2] - a[2][2]) + dt*muCargoTranslation*(Fsteric[0] + Ftrap[0] + FmRadial[0][0] + FmRadial[1][0] + FmRadial[2][0]) + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[1],2) + pow(c[2],2) + a[0][1]*a[2][1] - c[1]*(a[0][1] + a[2][1]) + a[0][2]*a[2][2] - c[2]*(a[0][2] + a[2][2])))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[1] - a[2][1])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[0] - a[0][0])*(c[2] - a[2][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[1],2) + pow(c[2],2) + a[1][1]*a[2][1] - c[1]*(a[1][1] + a[2][1]) + a[1][2]*a[2][2] - c[2]*(a[1][2] + a[2][2])))*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][0] + sqrt(dt)*muAnchor[1]*FmTangential[1][0]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[0] - a[1][0])*(c[1] - a[2][1])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][1] + sqrt(dt)*muAnchor[1]*FmTangential[1][1]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[0] - a[1][0])*(c[2] - a[2][2])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][2] + sqrt(dt)*muAnchor[1]*FmTangential[1][2]))/muAnchor[1] + (sqrt(dt)*(muCargoTranslation + muAnchor[2] + muCargoRotation*(pow(c[1],2) + pow(c[2],2) - 2*c[1]*a[2][1] + pow(a[2][1],2) - 2*c[2]*a[2][2] + pow(a[2][2],2)))*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][0] + sqrt(dt)*muAnchor[2]*FmTangential[2][0]))/muAnchor[2] - (sqrt(dt)*muCargoRotation*(c[0] - a[2][0])*(c[1] - a[2][1])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][1] + sqrt(dt)*muAnchor[2]*FmTangential[2][1]))/muAnchor[2] - (sqrt(dt)*muCargoRotation*(c[0] - a[2][0])*(c[2] - a[2][2])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][2] + sqrt(dt)*muAnchor[2]*FmTangential[2][2]))/muAnchor[2];

            a1[2][1] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[1] - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[2] + sqrt(dt)*muCargoRotation*TorqeExt[2])*(c[0] - a[2][0]) + a[2][1] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[0] + sqrt(dt)*muCargoRotation*TorqeExt[0])*(c[2] - a[2][2]) + dt*muCargoTranslation*(Fsteric[1] + Ftrap[1] + FmRadial[0][1] + FmRadial[1][1] + FmRadial[2][1]) - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[0] - a[2][0])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[0],2) + pow(c[2],2) + a[0][0]*a[2][0] - c[0]*(a[0][0] + a[2][0]) + a[0][2]*a[2][2] - c[2]*(a[0][2] + a[2][2])))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[1] - a[0][1])*(c[2] - a[2][2])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[1] - a[1][1])*(c[0] - a[2][0])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][0] + sqrt(dt)*muAnchor[1]*FmTangential[1][0]))/muAnchor[1] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[0],2) + pow(c[2],2) + a[1][0]*a[2][0] - c[0]*(a[1][0] + a[2][0]) + a[1][2]*a[2][2] - c[2]*(a[1][2] + a[2][2])))*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][1] + sqrt(dt)*muAnchor[1]*FmTangential[1][1]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[1] - a[1][1])*(c[2] - a[2][2])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][2] + sqrt(dt)*muAnchor[1]*FmTangential[1][2]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[0] - a[2][0])*(c[1] - a[2][1])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][0] + sqrt(dt)*muAnchor[2]*FmTangential[2][0]))/muAnchor[2] + (sqrt(dt)*(muCargoTranslation + muAnchor[2] + muCargoRotation*(pow(c[0],2) + pow(c[2],2) - 2*c[0]*a[2][0] + pow(a[2][0],2) - 2*c[2]*a[2][2] + pow(a[2][2],2)))*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][1] + sqrt(dt)*muAnchor[2]*FmTangential[2][1]))/muAnchor[2] - (sqrt(dt)*muCargoRotation*(c[1] - a[2][1])*(c[2] - a[2][2])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][2] + sqrt(dt)*muAnchor[2]*FmTangential[2][2]))/muAnchor[2];

            a1[2][2] = sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[2] + sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[1] + sqrt(dt)*muCargoRotation*TorqeExt[1])*(c[0] - a[2][0]) - sqrt(dt)*(sqrt(2)*sqrt(DCargoRotation)*Rbc[0] + sqrt(dt)*muCargoRotation*TorqeExt[0])*(c[1] - a[2][1]) + a[2][2] + dt*muCargoTranslation*(Fsteric[2] + Ftrap[2] + FmRadial[0][2] + FmRadial[1][2] + FmRadial[2][2]) - (sqrt(dt)*muCargoRotation*(c[2] - a[0][2])*(c[0] - a[2][0])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][0] + sqrt(dt)*muAnchor[0]*FmTangential[0][0]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[2] - a[0][2])*(c[1] - a[2][1])*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][1] + sqrt(dt)*muAnchor[0]*FmTangential[0][1]))/muAnchor[0] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[0],2) + pow(c[1],2) + a[0][0]*a[2][0] - c[0]*(a[0][0] + a[2][0]) + a[0][1]*a[2][1] - c[1]*(a[0][1] + a[2][1])))*(sqrt(2)*sqrt(DAnchor[0])*Dba[0][2] + sqrt(dt)*muAnchor[0]*FmTangential[0][2]))/muAnchor[0] - (sqrt(dt)*muCargoRotation*(c[2] - a[1][2])*(c[0] - a[2][0])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][0] + sqrt(dt)*muAnchor[1]*FmTangential[1][0]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[2] - a[1][2])*(c[1] - a[2][1])*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][1] + sqrt(dt)*muAnchor[1]*FmTangential[1][1]))/muAnchor[1] + (sqrt(dt)*(muCargoTranslation + muCargoRotation*(pow(c[0],2) + pow(c[1],2) + a[1][0]*a[2][0] - c[0]*(a[1][0] + a[2][0]) + a[1][1]*a[2][1] - c[1]*(a[1][1] + a[2][1])))*(sqrt(2)*sqrt(DAnchor[1])*Dba[1][2] + sqrt(dt)*muAnchor[1]*FmTangential[1][2]))/muAnchor[1] - (sqrt(dt)*muCargoRotation*(c[0] - a[2][0])*(c[2] - a[2][2])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][0] + sqrt(dt)*muAnchor[2]*FmTangential[2][0]))/muAnchor[2] - (sqrt(dt)*muCargoRotation*(c[1] - a[2][1])*(c[2] - a[2][2])*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][1] + sqrt(dt)*muAnchor[2]*FmTangential[2][1]))/muAnchor[2] + (sqrt(dt)*(muCargoTranslation + muAnchor[2] + muCargoRotation*(pow(c[0],2) + pow(c[1],2) - 2*c[0]*a[2][0] + pow(a[2][0],2) - 2*c[1]*a[2][1] + pow(a[2][1],2)))*(sqrt(2)*sqrt(DAnchor[2])*Dba[2][2] + sqrt(dt)*muAnchor[2]*FmTangential[2][2]))/muAnchor[2];

            c1[0] = c[0] + sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[0] + dt*muCargoTranslation*Fsteric[0] + dt*muCargoTranslation*Ftrap[0] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[0])*Dba[0][0])/muAnchor[0] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[1])*Dba[1][0])/muAnchor[1] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[2])*Dba[2][0])/muAnchor[2] + dt*muCargoTranslation*FmRadial[0][0] + dt*muCargoTranslation*FmRadial[1][0] + dt*muCargoTranslation*FmRadial[2][0] + dt*muCargoTranslation*FmTangential[0][0] + dt*muCargoTranslation*FmTangential[1][0] + dt*muCargoTranslation*FmTangential[2][0];

            c1[1] = c[1] + sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[1] + dt*muCargoTranslation*Fsteric[1] + dt*muCargoTranslation*Ftrap[1] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[0])*Dba[0][1])/muAnchor[0] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[1])*Dba[1][1])/muAnchor[1] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[2])*Dba[2][1])/muAnchor[2] + dt*muCargoTranslation*FmRadial[0][1] + dt*muCargoTranslation*FmRadial[1][1] + dt*muCargoTranslation*FmRadial[2][1] + dt*muCargoTranslation*FmTangential[0][1] + dt*muCargoTranslation*FmTangential[1][1] + dt*muCargoTranslation*FmTangential[2][1];

            c1[2] = c[2] + sqrt(2)*sqrt(DCargoTranslation)*sqrt(dt)*Dbc[2] + dt*muCargoTranslation*Fsteric[2] + dt*muCargoTranslation*Ftrap[2] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[0])*Dba[0][2])/muAnchor[0] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[1])*Dba[1][2])/muAnchor[1] + (sqrt(2)*sqrt(dt)*muCargoTranslation*sqrt(DAnchor[2])*Dba[2][2])/muAnchor[2] + dt*muCargoTranslation*FmRadial[0][2] + dt*muCargoTranslation*FmRadial[1][2] + dt*muCargoTranslation*FmRadial[2][2] + dt*muCargoTranslation*FmTangential[0][2] + dt*muCargoTranslation*FmTangential[1][2] + dt*muCargoTranslation*FmTangential[2][2];

//            theta1[0] = (sqrt(2)*sqrt(DCargoRotation)*sqrt(dt)*muAnchor[0]*muAnchor[1]*muAnchor[2]*Rbc[0] + sqrt(2)*sqrt(dt)*muCargoRotation*sqrt(DAnchor[0])*muAnchor[1]*muAnchor[2]*(c[2]*Dba[0][1] - a[0][2]*Dba[0][1] + (-c[1] + a[0][1])*Dba[0][2]) + muAnchor[0]*(sqrt(2)*sqrt(dt)*muCargoRotation*sqrt(DAnchor[1])*muAnchor[2]*(c[2]*Dba[1][1] - a[1][2]*Dba[1][1] + (-c[1] + a[1][1])*Dba[1][2]) + muAnchor[1]*(sqrt(2)*sqrt(dt)*muCargoRotation*sqrt(DAnchor[2])*(c[2]*Dba[2][1] - a[2][2]*Dba[2][1] + (-c[1] + a[2][1])*Dba[2][2]) + muAnchor[2]*(theta[0] + dt*muCargoRotation*(TorqeExt[0] - a[0][2]*FmTangential[0][1] - c[1]*FmTangential[0][2] + a[0][1]*FmTangential[0][2] - a[1][2]*FmTangential[1][1] - c[1]*FmTangential[1][2] + a[1][1]*FmTangential[1][2] - a[2][2]*FmTangential[2][1] + c[2]*(FmTangential[0][1] + FmTangential[1][1] + FmTangential[2][1]) - c[1]*FmTangential[2][2] + a[2][1]*FmTangential[2][2])))))/(muAnchor[0]*muAnchor[1]*muAnchor[2]);

//            theta1[1] = (sqrt(2)*sqrt(DCargoRotation)*sqrt(dt)*muAnchor[0]*muAnchor[1]*muAnchor[2]*Rbc[1] + sqrt(2)*sqrt(dt)*muCargoRotation*sqrt(DAnchor[0])*muAnchor[1]*muAnchor[2]*(-(c[2]*Dba[0][0]) + a[0][2]*Dba[0][0] + (c[0] - a[0][0])*Dba[0][2]) + muAnchor[0]*(sqrt(2)*sqrt(dt)*muCargoRotation*sqrt(DAnchor[1])*muAnchor[2]*(-(c[2]*Dba[1][0]) + a[1][2]*Dba[1][0] + (c[0] - a[1][0])*Dba[1][2]) + muAnchor[1]*(sqrt(2)*sqrt(dt)*muCargoRotation*sqrt(DAnchor[2])*(-(c[2]*Dba[2][0]) + a[2][2]*Dba[2][0] + (c[0] - a[2][0])*Dba[2][2]) + muAnchor[2]*(theta[1] + dt*muCargoRotation*(TorqeExt[1] + a[0][2]*FmTangential[0][0] + c[0]*FmTangential[0][2] - a[0][0]*FmTangential[0][2] + a[1][2]*FmTangential[1][0] + c[0]*FmTangential[1][2] - a[1][0]*FmTangential[1][2] + a[2][2]*FmTangential[2][0] - c[2]*(FmTangential[0][0] + FmTangential[1][0] + FmTangential[2][0]) + c[0]*FmTangential[2][2] - a[2][0]*FmTangential[2][2])))))/(muAnchor[0]*muAnchor[1]*muAnchor[2]);

//            theta1[2] = (sqrt(2)*sqrt(DCargoRotation)*sqrt(dt)*muAnchor[0]*muAnchor[1]*muAnchor[2]*Rbc[2] + sqrt(2)*sqrt(dt)*muCargoRotation*sqrt(DAnchor[0])*muAnchor[1]*muAnchor[2]*(c[1]*Dba[0][0] - a[0][1]*Dba[0][0] + (-c[0] + a[0][0])*Dba[0][1]) + muAnchor[0]*(sqrt(2)*sqrt(dt)*muCargoRotation*sqrt(DAnchor[1])*muAnchor[2]*(c[1]*Dba[1][0] - a[1][1]*Dba[1][0] + (-c[0] + a[1][0])*Dba[1][1]) + muAnchor[1]*(sqrt(2)*sqrt(dt)*muCargoRotation*sqrt(DAnchor[2])*(c[1]*Dba[2][0] - a[2][1]*Dba[2][0] + (-c[0] + a[2][0])*Dba[2][1]) + muAnchor[2]*(theta[2] + dt*muCargoRotation*(TorqeExt[2] - a[0][1]*FmTangential[0][0] - c[0]*FmTangential[0][1] + a[0][0]*FmTangential[0][1] - a[1][1]*FmTangential[1][0] - c[0]*FmTangential[1][1] + a[1][0]*FmTangential[1][1] - a[2][1]*FmTangential[2][0] + c[1]*(FmTangential[0][0] + FmTangential[1][0] + FmTangential[2][0]) - c[0]*FmTangential[2][1] + a[2][0]*FmTangential[2][1])))))/(muAnchor[0]*muAnchor[1]*muAnchor[2]);

            break;

        default:
            printf("Bad value for total_motors\n");
    }
}
