function summary=import_summary(params,localpath,run_name)
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/Matt/Google Drive/project_data/Motor_Freedom_data/numerical_tests/anchor_drag.0_Summary.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/10/21 10:54:06

%% Initialize variables.

filename = [localpath '/' run_name '_Summary.txt'];

if ~exist(filename,'file')
    error([filename ' doesnt exist!'])
end
delimiter = ' ';
startRow = 2;

N=params.N;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
% For more information, see the TEXTSCAN documentation.
%formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

fileID = fopen(filename,'r');

piece1=repmat('%f',1,5+3+3+3*sum(N));
piece2='%[^\n\r]';

formatSpec=strcat(piece1,piece2);

%% second time

dataArray = textscan(fileID, formatSpec, ...
    'Delimiter', delimiter, 'MultipleDelimsAsOne', true, ...
    'HeaderLines' , startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Allocate imported array to column variable names

% for importi=1:num
%     dataArray{:,importi}=dataArray{:,importi}(~isnan(dataArray{:,importi}));
% end

summary=struct;

summary.repeat = dataArray{:,1};
summary.step = dataArray{:, 2};
summary.t_final = dataArray{:, 3};
summary.exit_cond = dataArray{:, 4};
summary.success = dataArray{:,5};
summary.success=logical(summary.success);

summary.max_dist=[dataArray{:,6:8}];

num=5+3+3;

summary.last_bound_center = [dataArray{:, num-2} ...
    dataArray{:, num-1} ...
    dataArray{:, num}]';

summary.last_bound_head=cell(2,1);
summary.last_bound_head{1}=zeros(N(1),size(summary.repeat,1),3);
summary.last_bound_head{2}=zeros(N(2),size(summary.repeat,1),3);

for m=1:2
    for n=1:N(m)
        if m==1
            column=num+1+(n-1)*3;
        else
            column=num+1+N(1)*3+(n-1)*3;
        end
        summary.last_bound_head{m}(n,:,:)=...
            [dataArray{:,column:column+2}];
    end
end


%% Clear temporary variables
%clearvars  m n;
end