function locs=import_locs(params,localpath,run_name)
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/Matt/Google Drive/Allard Lab/Motor Freedom Project/src/macrun1
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/04/19 02:12:49

%% Initialize variables.

filename = [localpath '/' run_name '_Center_and_Anchors.txt'];
disp(['Importing locs from ' filename])
delimiter = ' ';
startRow = 2;

N=params.N;

%% Format string for each line of text:

%need a %f for each column of numbers to read in
%step, time, center x,y,z = 5
%x,y,z for each motor = 3*(N_k+N_d)
piece1=repmat('%f',1,6+3*(N(1)+N(2)));
piece2='%[^\n\r]';

formatSpec=strcat(piece1,piece2);

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names

locs=struct;

repeat = dataArray{:, 1};
locs.step = dataArray{:, 2};
locs.t_arr = dataArray{:, 3};

locs.center = [dataArray{:, 4} dataArray{:, 5} dataArray{:, 6}];

%% if there are times for each repeat, shape outputs

locs = transform_vars(locs,repeat);

%%

%locs.loc_rec{motor_type,repeat}(timestep,dimension,motor number)
locs.loc_rec=cell(2,max(repeat));

if max(N)>0

    for i=1:max(repeat)

        for m=1:2
            for n=1:N(m)

                ind=7+(m-1)*N(1)*3+(n-1)*3;
                locs.loc_rec{m,i}(:,:,n)=[dataArray{ind}(repeat==i)...
                    dataArray{ind+1}(repeat==i) ...
                    dataArray{ind+2}(repeat==i)];

            end
        end

    end %repeat

else
    % no motors
end


%% Clear temporary variables
%clearvars ind temp temp2 m n step piece1 piece2...
%    filename delimiter startRow formatSpec fileID dataArray ans;
end
