%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/Matt/Google Drive/project_data/MT_intersection_data/TOW_output_test/switch_fraction_single_ToW.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/04/14 15:05:48

%% Initialize variables.
filename = [localpath '/' run_name '_ToW.txt'];

if ~exist(filename,'file')
    error([filename ' doesnt exist!'])
end
delimiter = ' ';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
repeat = dataArray{:, 1};
step = dataArray{:, 2};
t_arr = dataArray{:, 3};
ToW_time = dataArray{:, 4};
ToWs = dataArray{:, 5};
F_ToW0 = dataArray{:, 6};
F_ToW1 = dataArray{:, 7};
F2_ToW0 = dataArray{:, 8};
F2_ToW1 = dataArray{:, 9};
FMT_ToW0 = dataArray{:, 10};
FMT_ToW1 = dataArray{:, 11};
F2MT_ToW0 = dataArray{:, 12};
F2MT_ToW1 = dataArray{:, 13};
FMTb_ToW0 = dataArray{:, 14};
FMTb_ToW1 = dataArray{:, 15};
FH_ToW0 = dataArray{:, 16};
FH_ToW1 = dataArray{:, 17};
F2H_ToW0 = dataArray{:, 18};
F2H_ToW1 = dataArray{:, 19};
Fteam_ToW0 = dataArray{:, 20};
Fteam_ToW1 = dataArray{:, 21};
FonMT_ToW00 = dataArray{:, 22};
FonMT_ToW01 = dataArray{:, 23};
FonMT_ToW10 = dataArray{:, 24};
FonMT_ToW11 = dataArray{:, 25};
FonOT_ToW0 = dataArray{:, 26};
FonOT_ToW1 = dataArray{:, 27};
n_ToW0 = dataArray{:, 28};
n_ToW1 = dataArray{:, 29};
off_count0 = dataArray{:, 30};
off_count1 = dataArray{:, 31};
stretch_amount = dataArray{:, 32};
stretch_time = dataArray{:, 33};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;