%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/Matt/Google Drive/project_data/Motor_Freedom_data/numerical_tests/anchor_drag.0_Summary.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/10/21 10:54:06

%% Initialize variables.

summimport=struct;

summimport.filename = [localpath '/' run_name '_Summary.txt'];

if ~exist(summimport.filename,'file')
    error([summimport.filename ' doesnt exist!'])
end
summimport.delimiter = ' ';
summimport.startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
% For more information, see the TEXTSCAN documentation.
%formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

summimport.num=24;

%piece1=repmat('%f',1,num+3+2*3*(N(1)+N(2)));
summimport.piece1=repmat('%f',1,summimport.num);
summimport.piece2='%[^\n\r]';

summimport.formatSpec=strcat(summimport.piece1,summimport.piece2);

%% Open the text file.
summimport.fileID = fopen(summimport.filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
summimport.dataArray2 = textscan(summimport.fileID, summimport.formatSpec, ...
    'Delimiter', summimport.delimiter, 'MultipleDelimsAsOne', true, ...
    'HeaderLines' ,summimport.startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

N1 = summimport.dataArray2{:,11};

fclose(summimport.fileID);

summimport.fileID = fopen(summimport.filename,'r');

summimport.piece1=repmat('%f',1,summimport.num+3+2*3*(N1(1)+N(2))+(N1(1)+N(2)));
summimport.piece2='%[^\n\r]';

summimport.formatSpec=strcat(summimport.piece1,summimport.piece2);

%% second time

summimport.dataArray = textscan(summimport.fileID, summimport.formatSpec, ...
    'Delimiter', summimport.delimiter, 'MultipleDelimsAsOne', true, ...
    'HeaderLines' , summimport.startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(summimport.fileID);

%% Allocate imported array to column variable names

% for importi=1:num
%     dataArray{:,importi}=dataArray{:,importi}(~isnan(dataArray{:,importi}));
% end

repeat = summimport.dataArray{:,1};
step = summimport.dataArray{:, 2};
t_final = summimport.dataArray{:, 3};
exit_cond = summimport.dataArray{:, 4};
success = summimport.dataArray{:,5};
success=logical(success);
D_anchor = summimport.dataArray{:, 6};
eps_0 = summimport.dataArray{:, 7};
pi_0 = summimport.dataArray{:, 8};
offset = summimport.dataArray{:, 9};
R = summimport.dataArray{:,10};
N1 = summimport.dataArray{:,11};
F1 = summimport.dataArray{:,12};
theta_c = summimport.dataArray{:,13};
MT_angle = summimport.dataArray{:,14};
F_d1 = summimport.dataArray{:,15};
eta = summimport.dataArray{:,16};
k_m1 = summimport.dataArray{:,17};

MTvec{2}=[summimport.dataArray{:,summimport.num-6} ...
    summimport.dataArray{:,summimport.num-5} ...
    summimport.dataArray{:,summimport.num-4}];

ToW_time = summimport.dataArray{:,summimport.num-3};

last_bound_center = [summimport.dataArray{:, summimport.num-2} ...
    summimport.dataArray{:, summimport.num-1} ...
    summimport.dataArray{:, summimport.num}];

center_final = [summimport.dataArray{:, summimport.num+1} ...
    summimport.dataArray{:, summimport.num+2} ...
    summimport.dataArray{:, summimport.num+3}];
% type0motor0_x = dataArray{:, 10};
% type0motor0_y = dataArray{:, 11};
% type0motor0_z = dataArray{:, 12};

N(1)=N1(1);

locs_final=cell(2,1);
locs_final{1}=cell(N(1),1);
locs_final{2}=cell(N(2),2);

for summimportm=1:2
    for summimportn=1:N(summimportm)
        if summimportm==1
            summimport.column=summimport.num+4+(summimportn-1)*3;
        else
            summimport.column=summimport.num+4+N(1)*3+(summimportn-1)*3;
        end
        locs_final{summimportm}{summimportn}=...
            [summimport.dataArray{:,summimport.column:summimport.column+2}];
    end
end

summimport.last_locs_col=summimport.num+4+3*(N(1)+N(2))-1;

head_final=cell(2,1);
head_final{1}=cell(N(1),1);
head_final{2}=cell(N(2),2);

for summimportm=1:2
    for summimportn=1:N(summimportm)
        if summimportm==1
            summimport.column=summimport.last_locs_col+1+(summimportn-1)*3;
        else
            summimport.column=summimport.last_locs_col+1+N(1)*3+(summimportn-1)*3;
        end
        head_final{summimportm}{summimportn}=...
            [summimport.dataArray{:,summimport.column:summimport.column+2}];
    end
end

summimport.last_head_col=summimport.num+4+3*(N(1)+N(2))-1+ 3*(N(1)+N(2));

bound_final=cell(2,1);
bound_final{1}=cell(N(1),1);
bound_final{2}=cell(N(2),2);

for summimportm=1:2
    for summimportn=1:N(summimportm)
        if summimportm==1
            summimport.column=summimport.last_head_col+1+(summimportn-1);
        else
            summimport.column=summimport.last_head_col+1+N(1)+(summimportn-1);
        end
        bound_final{summimportm}{summimportn}=...
            [summimport.dataArray{:,summimport.column}];
    end
end


%% Clear temporary variables
clearvars summimport summimportm summimportn;
