bead0:
	gcc -O3 driveMotors.c -o motors.x -lm -Dbead0 -Wno-unused-result

bead5:
	gcc -O3 driveMotors.c -o motors.x -lm -Dbead5 -Wno-unused-result

bead10:
	gcc -O3 driveMotors.c -o motors.x -lm -Dbead10 -Wno-unused-result

bead20:
	gcc -O3 driveMotors.c -o motors.x -lm -Dbead20 -Wno-unused-result

bead30:
	gcc -O3 driveMotors.c -o motors.x -lm -Dbead20 -Wno-unused-result

bead50:
	gcc -O3 driveMotors.c -o motors.x -lm -Dbead50 -Wno-unused-result

bead101:
	gcc -O3 driveMotors.c -o motors.x -lm -Dbead101 -Wno-unused-result

free0:
	gcc -O3 driveMotors.c -o motors.x -lm -Dfree0 -Wno-unused-result

free5:
	gcc -O3 driveMotors.c -o motors.x -lm -Dfree5 -Wno-unused-result

free10:
	gcc -O3 driveMotors.c -o motors.x -lm -Dfree10 -Wno-unused-result

free20:
	gcc -O3 driveMotors.c -o motors.x -lm -Dfree20 -Wno-unused-result

free30:
	gcc -O3 driveMotors.c -o motors.x -lm -Dfree30 -Wno-unused-result
