bead0:
	gcc -O3 driveMotors.c -o motors.x -lm -Dbead0

bead5:
	gcc -O3 driveMotors.c -o motors.x -lm -Dbead5

bead10:
	gcc -O3 driveMotors.c -o motors.x -lm -Dbead10

bead20:
	gcc -O3 driveMotors.c -o motors.x -lm -Dbead20

bead30:
	gcc -O3 driveMotors.c -o motors.x -lm -Dbead20

bead50:
	gcc -O3 driveMotors.c -o motors.x -lm -Dbead50

bead101:
	gcc -O3 driveMotors.c -o motors.x -lm -Dbead101

free0:
	gcc -O3 driveMotors.c -o motors.x -lm -Dfree0

free5:
	gcc -O3 driveMotors.c -o motors.x -lm -Dfree5

free10:
	gcc -O3 driveMotors.c -o motors.x -lm -Dfree10

free20:
	gcc -O3 driveMotors.c -o motors.x -lm -Dfree20

free30:
	gcc -O3 driveMotors.c -o motors.x -lm -Dfree30
